### ISSUE TITLE
'이펙티브 자바'도 동영상으로 올리실 예정이신가요?

### ISSUE THREAD

**Issue by writer0713** [keesun/study#3]
혼자 공부하기에는 내용이 좀 어려웠었는데 관련해서 README.md에 업데이트가 되어 여쭤봅니다.
혹시 이펙티브 자바도 동영상으로 찍으실 계획이 있으신가요?

**Comment by keesun** [comment]
네 저작권(?) 때문에 고민중인데요. 책을 보는게 아니라 제가 요약한걸 보면서 방송하면 괜찮지 않을까 싶기도 하고요.

**Comment by writer0713** [comment]
@keesun 
유투브에 보면 이전에 이펙티브자바 책으로 스터디를 진행하는 동영상이 있습니다. 그리고 외국에서도 이펙티브 자바에 대한 해설을 하는 동영상도 꽤 있구요..ㅎㅎ 큰 문제가 되지 않을듯 하다는 개인적인 생각입니다. 꼭 좀 해주시면 좋겠습니다 ㅜㅜ 혼자 공부하기에는 너무 어렵네요..

**Comment by keesun** [comment]
그렇군요. 감사합니다. 해볼께요. ㅋㅋ
