### ISSUE TITLE
Effective Java Item 1과 Builder pattern의 사용처의 차이가 궁금합니다.

### ISSUE THREAD

**Issue by mingyu-lee** [keesun/study#7]
안녕하세요 초급 자바웹개발자입니다. 
기선님 영상과 요약글 잘 보고 있고 업로드 해주셔서 정말 감사합니다.

이펙티브 자바 1 요약하신 내용과
빌더 패턴의 구성 문법의 차이는 이해가 되는데요.

실제로 빌더 패턴을 사용하는 경우는 알겠는데
static 팩토리 메서드를 활용하는 경우는 어떤 경우이고
이 둘의 사용처 차이를 어떻게 설명해야 좋을까요?

**Comment by cheese10yun** [comment]
@mingyu-lee 
저도 부족하지만 제가 느낀것에 대해서 말씀드리자면 

빌더 패턴, 정적 팩토리 메서드는 객체를 만드는 것에 대해서는 같은 기능이라고 보입니다. 

하지만 해결하려는 문제는 다르다고 생각합니다.

빌더 패턴같은 경우에는 객체를 생성할 경우 넘겨 받아야 할 인자가 많으면 객체를 생성할 때 많은 어려움이 있습니다.

만약 user를 생성할 때 필요한 인자가 10개 인데 이 중에 2개는 필수 값이고 나머지 것들은 옵션값이라는 경우일 때 일단 적인 생성자 방법, 자바 빈 패턴으로는 표현하기가 어렵습니다. 이러한 문제를 해결하기 좋은 것이 빌더 패턴이라고 생각합니다.

정적 팩토리 메서드는 다양한 장점들이 있지만, 객체를 조금 더 명확하게 생성할 수 있다는 것이 중요한 거 같습니다.

가장 대표적안 것이 enum 클래스의 valueOf 메서드들인데요
valueOf는 넘겨 받은 인자 값으로 해당 객체를 리턴해주는 메서드 입니다. 객체를 리턴해줘야 하니 객체를 만들어야 할 테지요. 이처럼 객체를 생성할 때 메서드 네이밍을 통해서 해당 기능을 책임 부여할 수 있는 특징이 있습니다.

그밖에도 매번 새로운 객체를 생성할 필요가 없다는 점등 다양한 이점이 있습니다.

요약 정리하면
* **빌더 패턴은 여러 인자를 받아 객체를 생성할 때 사용**
* **정적 팩토리 메서드는 객체를 만들 때 그 쓰임새가 명확하게 사용할 수 있다**

저도 주니어 개발자라서 다른 분들 의견도 반드시 참고해주시는 게 좋을 거 같습니다.

**Comment by keesun** [comment]
빌더 패턴이 1번 아이템에서 말하는 static factory 메소드를 활용하라는 것의 한 예라고 생각해도 좋을거 같습니다. 아니면 반대로 빌더 패턴을 구현하는 방법 중 하나가 static factory라고 볼 수도 있을거구요. @cheese10yun 님께서 댓글을 잘 달아주셔서 이 이슈는 닫아도 될거 같습니다. 두분 모두 좋은 질문과 답변 감사합니다. :)
