### ISSUE TITLE
자료구조와 알고리즘의 중요성에 대해 알려주시는 건 어떨까요?

### ISSUE THREAD

**Issue by gameover3** [keesun/study#8]
안녕하세요. Backend 개발을 하고 있는 개발자입니다.

 유투브에 영상 덕분에 많은 깨우침을 느끼고 개발자입니다. ^-^
다름이 아니고 제가 요근래 고민하고 있는 문제인데요. 저뿐만 아니라 "다른 분들에게도 좋은 정보가 되지 않을까?" 해서 글을 올려봅니다.ㅎㅎ

 제 얘길 조금 하자면 전 지금 이직을 준비하고 있는데요. 중견기업, 대기업에서 codility로 코딩테스트를 보는게 일반화가 됐더라구요. 백기선님도 아시겠지만 codility 문제는 영어로 알고리즘 문제가 나오더라구요. 좀 부끄러운 얘기이긴 하지만 실무에서는 "모델을 어떻게 설계하면 중복된 코드를 피할 수 있을까" 혹은 "잘 짜여진 라이브러리는 무엇이며 이를 어떻게 잘 활용할까"로 접근을 많이 했었거든요.  물론 좀 복잡한 프로세스를 만들 때는 코드상 시간을 찍어보며 코딩테스트를 하긴 했지만요. 아무튼 그래서 낑낑대며 문제를 푸는데 Tesk Score는 100%지만, Correctness 혹은 Performance 점수가 낮게 책정되는 경우, 수학적 이론을 알아야만 풀 수 있는 경우, 마지막으로 아예 문제를 이해 못하는 경우도 있더라구요. 그래서 "내가 언제 자료구조와 알고리즘에 대해 고민해봤을까?" 생각을 해보니 학교다닐 때와 정보처리기사 자격증을 취득할 때를 제외하곤 없더라구요. 지금부터라도 자료구조와 알고리즘에 대해 공부를 해볼까 합니다.
 사실 대용량 트래픽을 대비해서 알고리즘이(시간복잡도, 공간복잡도) 얼마나 중요한지는 깨닫고 있긴 하지만, 그 외적으로 자료구조나 알고리즘에 대한 중요성을 알려주실 수 있을까요? 그리고 공부를 어디서부터 시작할지가 좀 막막하긴 하더라구요. 그래서 추천 도서와 효율적으로 공부할 수 있을지 나만의 노하우(팁)이 있다면 알려주시면 좋을 것 같아요~

- 궁금한 사항 정리
1. 자료구조와 알고리즘의 중요성(경험담 및 알고리즘을 꾸준히 공부하고 계시는 지도...ㅎㅎ)
2. 추천 도서 및 효율적인 공부 방법

끝까지 읽어 주셔서 감사합니다.ㅎㅎ

**Comment by keesun** [comment]
회사 마다 또는 인터뷰어마다 코딩 퀴즈의 목적이 다들 좀 달라서 뭐라고 답하는게 어려운 질문이긴한데요. 공부하는 입장과 또 인터뷰를 보는 제 입장에서 그 둘을 공부하는 목적은 **문제 분석 그리고 해결 능력**을 키우기 위한 것입니다. 따라서 지나치게 복잡한 알고리즘은 딱히 공부할 필요가 없지만 그래도 가끔씩은 그런 문제를 어떻게 해결하는지 그 과정을 따라 풀어보는건 기본 소양을 늘리는데 중요하단 생각이 드네요.

요즘은 강좌 만든다고 (핑계삼아) 공부를 안하고 있는데 (이건 잘못된거죠;; 저도 꾸준히 해야하는데 말이죠;) leetcode라는 웹사이트에서 매일 문제 하나씩 푸는걸 목표로 공부했던 적이 있습니다.

온라인 사이트에서 풀이도 나오고 링크 걸어서 다른 사람들하고 토론해보는것도 좋은거 같습니다.
